dependencies:
- name: common
  version: 0.0.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: catalogue_db
  version: 0.0.3-master
  condition: mysql.enabled, global.mysql.enabled
  repository: "@cloudpossedemo"
  import-values:
  - child: mysql
    parent: mysql