dependencies:
- name: common
  version: 0.0.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: cloudpossedemo/catalogue-db
  version: 0.3.0-master
  condition: db.enabled, global.db.enabled
  repository: "@cloupossedemo"